# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cell_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='health_insurance_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
