# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_auto_20161002_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='work_number',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
