# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20161002_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cell_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_insurance_number',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
