# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_auto_20161002_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('patient_username', models.CharField(max_length=100)),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_insurance_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='physician',
            name='work_number',
            field=models.IntegerField(default=0),
        ),
    ]
