# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-31 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_auto_20161002_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cell_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
