# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 22:12
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_auto_20161002_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cell_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default=datetime.datetime(2016, 11, 6, 22, 12, 17, 604329, tzinfo=utc), max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default=datetime.datetime(2016, 11, 6, 22, 12, 24, 452238, tzinfo=utc), max_length=16, primary_key=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 11, 6, 22, 12, 34, 724767, tzinfo=utc), max_length=20, primary_key=True, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='first_name',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=16, primary_key=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=200, primary_key=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(max_length=50, primary_key=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='physician',
            name='last_name',
            field=models.CharField(default='lastname', max_length=100),
        ),
    ]
