# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-31 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_auto_20161031_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
    ]
