# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_auto_20161107_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(max_length=50, primary_key=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
