# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-31 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_auto_20161031_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
