# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
