# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_auto_20161107_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=100)),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('work_number', models.IntegerField(default=0)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
