# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-31 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_patient_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
