# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0016_auto_20161104_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
