# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_auto_20161107_0123'),
        ('System', '0021_auto_20161104_2250'),
    ]

    operations = [
    ]
